apiVersion: v1
kind: Service
metadata:
  name: todosbackend
spec:
  selector:
    app: todosbackend
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todosbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todosbackend
  template:
    metadata:
      labels:
        app: todosbackend
    spec:
      containers:
        - name: todosbackend
          image: mahmoodsultan/devops-backend:v0.0.2
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: todoapp-secrets
                  key: mongo-uri
            - name: NODE_ENV
              value: development
            - name: TODO_PORT
              value: "8080"
          imagePullPolicy: Always
