name: CI-CD

on:
  push:
    branches: [ devops-phase2 ]
  pull_request:
    branches: [ develop ]
  
jobs:
  build_node_app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]        
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          npm install
          npm ci
  push_image_to_Docker_Hub:
      runs-on: ubuntu-latest
      needs: [build_node_app1]
      steps:
        - name: checkout repo
          uses: actions/checkout@v2
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/devops-backend:phase2-v2